spring:
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: ${KEY_CLOAK_ISSUER_URI}
            jwk-set-uri: ${KEY_CLOAK_ISSUER_URI}/${JWK_SET_URI}
  application:
    name: pet.consumer
server:
  port: 8789

